"""empty message

Revision ID: 71982b2b4ef1
Revises: b47ecf15f9ce
Create Date: 2020-04-18 10:01:01.795574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71982b2b4ef1'
down_revision = 'b47ecf15f9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ShowToArtist',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], ),
    sa.PrimaryKeyConstraint('show_id', 'artist_id')
    )
    op.create_table('ShowToVenue',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('show_id', 'venue_id')
    )
    op.add_column('Show', sa.Column('venue_image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_image_link')
    op.drop_table('ShowToVenue')
    op.drop_table('ShowToArtist')
    # ### end Alembic commands ###
