"""empty message

Revision ID: a85abc69fce3
Revises: 53a94f573b36
Create Date: 2020-05-03 18:02:09.330454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85abc69fce3'
down_revision = '53a94f573b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ShowToArtist')
    op.drop_table('ShowToVenue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ShowToVenue',
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='ShowToVenue_show_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='ShowToVenue_venue_id_fkey'),
    sa.PrimaryKeyConstraint('show_id', 'venue_id', name='ShowToVenue_pkey')
    )
    op.create_table('ShowToArtist',
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='ShowToArtist_artist_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='ShowToArtist_show_id_fkey'),
    sa.PrimaryKeyConstraint('show_id', 'artist_id', name='ShowToArtist_pkey')
    )
    # ### end Alembic commands ###
